name: "Enforce conventions"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened

permissions:
  pull-requests: read

jobs:
  lint-pr:
    name: Validate PR title follows Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50 # v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # We may not need a scope on every commit (i.e. repo-level change).
          #
          # feat!: read config consistently
          # feat(redis): support for clustering
          # chore(redis): update tests
          # fix(redis): trim connection string
          # ^    ^    ^
          # |    |    |__ Subject
          # |    |_______ Scope
          # |____________ Type: it can end with a ! to denote a breaking change.
          requireScope: false
          # Scope should be lowercase.
          disallowScopes: |
            [A-Z]+
          # ensures the subject doesn't start with an uppercase character.
          subjectPattern: ^(?![A-Z]).+$
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            didn't match the configured pattern. Please ensure that the subject
            doesn't start with an uppercase character.
          types: |
            security
            fix
            feat
            docs
            chore
            deps

      - name: Detect if the Pull Request was sent from the main branch
        if: "${{ github.head_ref == 'main' }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr close --comment "This Pull Request has been automatically closed because it was sent from the fork's main branch. Please use a different branch so that the maintainers can contribute to your Pull Request."
          exit 1
