name: Tests against Latest Docker Moby

on:
  schedule:
    # nightly build, at 23:59 CEST
    - cron:  '59 23 * * *'

jobs:
  test_latest_moby:
    strategy:
      matrix:
        rootless-docker: [true, false]
        containerd-integration: [true, false]

    name: "Core tests using latest moby/moby"
    runs-on: 'ubuntu-latest'
    continue-on-error: true
    steps:
      - name: Set the Docker Install type
        run: |
          echo "docker_install_type=${{ matrix.rootless-docker == true && 'Rootless' || 'Rootful' }}" >> "$GITHUB_ENV"
          echo "containerd_integration=${{ matrix.containerd-integration == true && 'containerd' || '' }}" >> "$GITHUB_ENV"

      - name: Check out code into the Go module directory
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Set up Go
        uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5
        with:
            go-version-file: 'go.mod'
            cache-dependency-path: 'go.sum'
        id: go

      - name: modVerify
        run: go mod verify

      - name: modTidy
        run: go mod tidy

      - name: Install Nightly Docker
        uses: crazy-max/ghaction-setup-docker@master
        with:
          rootless: ${{ matrix.rootless-docker }}
          version: type=image,tag=master
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": ${{ matrix.containerd-integration }}
              }
            }

      - name: go test
        timeout-minutes: 30
        run: make test-unit

      - name: Create slack payload file
        if: failure()
        run: |
          cat <<EOF > ./payload-slack-content.json
          {
              "tc_project": "testcontainers-go",
              "tc_docker_install_type": "${docker_install_type}",
              "tc_containerd_integration": "${containerd_integration}",
              "tc_github_action_url": "${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}/attempts/${GITHUB_RUN_ATTEMPT}",
              "tc_github_action_status": "FAILED",
              "tc_slack_channel_id": "${{ secrets.SLACK_DOCKER_LATEST_CHANNEL_ID }}"
          }

      - name: Notify to Slack on failures
        if: failure()
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload-file-path: "./payload-slack-content.json"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_DOCKER_LATEST_WEBHOOK }}
