name: Sonar Bulk Operations

on:
  workflow_dispatch:
    inputs:
      operation:
        description: 'Operation to perform'
        required: true
        type: choice
        options:
          - createAll
          - deleteAll

jobs:
  bulk-operation:
    runs-on: shipfox-2vcpu-ubuntu-2404
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      
      - name: Execute Bulk Operation
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          chmod +x .github/scripts/sonar-manager.sh
          .github/scripts/sonar-manager.sh -a "${{ inputs.operation }}"
