name: Create Sonar Project

on:
  workflow_dispatch:
    inputs:
      project_name:
        description: 'Name of the project (without type prefix)'
        required: true
        type: string

jobs:
  create-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      
      - name: Create Sonar Project for module
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          chmod +x .github/scripts/sonar-manager.sh
          .github/scripts/sonar-manager.sh -a "create" -p "modules_${{ inputs.project_name }}"
